//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by thred.rc
//
#define IDS_FSELB                       1
#define IDS_FSELF                       2
#define IDS_FSELA                       3
#define IDS_FSELM                       4
#define IDS_SEL1FRM                     5
#define IDS_PIKOL                       6
#define IDS_UPON                        7
#define IDS_UPOF                        8
#define IDS_FGRPF                       10
#define IDS_ALL                         11
#define IDS_AUXTXT                      12
#define IDS_CPYRIT                      13
#define IDS_PNT                         14
#define IDS_HUP0                        15
#define IDS_HUP1                        16
#define IDS_HUP2                        17
#define IDS_HUP3                        18
#define IDS_HUP4                        19
#define IDS_KEY                         20
#define IDS_CLP                         21
#define IDS_EXP                         22
#define IDS_XPIRAD                      23
#define IDS_CNTR                        24
#define IDS_MAPLOD                      25
#define IDS_FRMOVR                      26
#define IDS_ROTIN                       27
#define IDS_SELC                        28
#define IDS_NSEL                        29
#define IDS_CONT                        30
#define IDS_ROTA                        31
#define IDS_FRM2                        32
#define IDS_FRML                        33
#define IDS_FRM3                        34
#define IDS_STMAX                       35
#define IDS_FRMN1                       36
#define IDS_COLU                        37
#define IDS_COLAL                       38
#define IDS_MRK                         39
#define IDS_FRMNO                       40
#define IDS_FRM2L                       41
#define IDS_NOTHR                       42
#define IDS_FNOPN                       43
#define IDS_REM1                        44
#define IDS_DST1                        45
#define IDS_BAKDT                       46
#define IDS_BAKDEL                      47
#define IDS_FDEL                        48
#define IDS_DELFRM                      49
#define IDS_END                         50
#define IDS_INSF                        51
#define IDS_PFAF2L                      52
#define IDS_DST2S                       53
#define IDS_BMAP                        54
#define IDS_SHOMAP                      55
#define IDS_MAPCHG                      56
#define IDS_SAVMAP                      57
#define IDS_FILSTCH                     58
#define IDS_BRDSTCH                     59
#define IDS_APSTCH                      60
#define IDS_FRMSEL                      61
#define IDS_FRM1MSG                     62
#define IDS_GRPMSG                      63
#define IDS_ROTAGIN                     64
#define IDS_SHOSEL                      65
#define IDS_REGP                        66
#define IDS_STAR                        67
#define IDS_SPIR                        68
#define IDS_HEART                       69
#define IDS_LENS                        70
#define IDS_EGG                         71
#define IDS_CLPS                        72
#define IDS_FRM3X                       73
#define IDS_ANGS                        74
#define IDS_FILSEL                      75
#define IDS_FILCR                       76
#define IDS_FGRPS                       77
#define IDS_UNGRP                       78
#define IDS_NOGRP                       79
#define IDS_NOHLP                       80
#define IDS_SAVDISC                     81
#define IDS_UNFIL                       82
#define IDS_REFIL                       83
#define IDS_SNAP2GRD                    84
#define IDS_RETRAC                      85
#define IDS_STCH_FRM                    86
#define IDS_SETMRK                      87
#define IDS_FSZ                         88
#define IDS_SETROTM                     89
#define IDS_RNGEND                      91
#define IDS_ROT                         92
#define IDS_ROTCMD                      93
#define IDS_CONVRIB                     94
#define IDS_ROTDUP                      95
#define IDS_CROP                        96
#define IDS_STCH2FRM                    97
#define IDS_FRMGUID                     98
#define IDS_SPLT                        99
#define IDS_CENT                        100
#define IDR_MENU1                       101
#define IDS_SETFRM                      101
#define IDS_FRMCLP                      102
#define IDS_SHRNK                       103
#define IDI_ICON1                       104
#define IDS_PRT                         104
#define IDS_SHRTKEY                     105
#define IDS_INVKEY                      106
#define IDS_DAYKEY                      108
#define IDS_SHRTF                       109
#define IDS_TRC0                        110
#define IDS_TRC1S                       111
#define IDS_TRC2                        112
#define IDS_TRC3                        113
#define IDD_DLOCK                       114
#define IDS_TRC4                        114
#define IDS_TRC1H                       117
#define IDD_TEAR                        117
#define IDS_SRCH                        118
#define IDD_WAV                         118
#define IDS_NUMPNT                      119
#define IDD_FETHDEF                     119
#define IDS_NUMFRM                      120
#define IDS_NUMSEL                      121
#define IDD_DASY                        121
#define IDS_NUMSCH                      122
#define IDD_TXTUR                       122
#define IDS_NUMFORM                     123
#define IDD_SIZ                         123
#define IDS_BOXSEL                      124
#define IDD_DESNAM                      124
#define IDS_RITER                       125
#define IDS_SAVFIL                      126
#define IDS_CLOS                        127
#define IDS_TOT                         128
#define IDS_LAYR                        129
#define IDS_CREAT                       130
#define IDS_FNOPNA                      131
#define IDS_NOTVER                      132
#define IDS_BADFIL                      133
#define IDS_ZEROL                       134
#define IDS_OVRLOK                      135
#define IDS_OVRIT                       136
#define IDS_FILROT                      137
#define IDS_THRED                       138
#define IDS_NUFIL                       139
#define IDS_SIZ                         140
#define IDS_TRIAL                       141
#define IDS_EMB                         142
#define IDS_ON                          143
#define IDS_OFF                         144
#define IDS_FMEN                        145
#define IDS_TXT0                        146
#define IDS_TXT1                        147
#define IDS_TXT2                        148
#define IDS_TXT3                        149
#define IDS_TXT4                        150
#define IDS_TXT5                        151
#define IDS_TXT6                        152
#define IDS_TXT7                        153
#define IDS_TXT8                        154
#define IDS_TXT9                        155
#define IDS_TXT10                       156
#define IDS_TXT11                       157
#define IDS_TXT12                       158
#define IDS_TXT13                       159
#define IDS_TXT14                       160
#define IDS_TXT15                       161
#define IDS_TXT16                       162
#define IDS_TXT17                       163
#define IDS_TXT18                       164
#define IDS_TXT19                       165
#define IDS_FIL0                        166
#define IDS_FIL1                        167
#define IDS_FIL2                        168
#define IDS_FIL3                        169
#define IDS_FIL4                        170
#define IDS_FIL5                        171
#define IDS_FIL6                        172
#define IDS_FIL7                        173
#define IDS_FIL8                        174
#define IDS_FIL9                        175
#define IDS_EDG0                        176
#define IDS_EDG1                        177
#define IDS_EDG2                        178
#define IDS_EDG3                        179
#define IDS_EDG4                        180
#define IDS_EDG5                        181
#define IDS_EDG6                        182
#define IDS_EDG7                        183
#define IDS_EDG8                        184
#define IDS_EDG9                        185
#define IDS_EDG10                       186
#define IDS_EDG11                       187
#define IDS_PRF0                        188
#define IDS_PRF1                        189
#define IDS_PRF2                        190
#define IDS_PRF3                        191
#define IDS_PRF4                        192
#define IDS_PRF5                        193
#define IDS_PRF6                        194
#define IDS_PRF7                        195
#define IDS_PRF8                        196
#define IDS_PRF9                        197
#define IDS_PRF10                       198
#define IDS_PRF11                       199
#define IDS_PRF12                       200
#define IDS_PRF13                       201
#define IDS_PRF14                       202
#define IDS_PRF15                       203
#define IDS_PRF16                       204
#define IDS_PRF17                       205
#define IDS_PRF18                       206
#define IDS_PRF19                       207
#define IDS_PRF20                       208
#define IDS_PRF21                       209
#define IDS_PRF22                       210
#define IDS_PRF23                       211
#define IDS_PRF24                       212
#define IDS_PRF25                       213
#define IDS_PRF26                       214
#define IDS_PRF27                       215
#define IDS_FRMPLUS                     217
#define IDS_FRMINUS                     218
#define IDS_OKENT                       219
#define IDS_CANCEL                      220
#define IDS_APCOL                       221
#define IDS_FREH                        222
#define IDS_BLUNT                       223
#define IDS_TAPR                        224
#define IDS_PNTD                        225
#define IDS_SQR                         226
#define IDS_DELST2                      227
#define IDS_NCOLCHG                     228
#define IDS_SAV                         229
#define IDS_DISC                        230
#define IDS_THRDBY                      231
#define IDS_STCHOUT                     232
#define IDS_STCHS                       233
#define IDS_FORMS                       236
#define IDS_HUPWID                      239
#define IDS_CREATBY                     241
#define IDS_CUSTHUP                     242
#define IDS_STCHP                       244
#define IDS_FRMP                        245
#define IDS_ENTROT                      246
#define IDS_NUDG                        247
#define IDS_NOSTCHSEL                   248
#define IDS_ZIG                         249
#define IDS_EDG12                       250
#define IDS_TXT20                       251
#define IDS_TXT21                       252
#define IDS_TXT22                       253
#define IDS_TXT23                       254
#define IDS_ALLX                        255
#define IDS_FTH0                        256
#define IDS_FTH1                        257
#define IDS_FTH2                        258
#define IDS_FTH3                        259
#define IDS_FTH4                        260
#define IDS_FTH5                        261
#define IDS_FIL10                       262
#define IDS_FTHCOL                      263
#define IDS_FTHTYP                      264
#define IDS_FTHBLND                     265
#define IDS_FTHUP                       266
#define IDS_FTHBOTH                     267
#define IDS_FTHSIZ                      268
#define IDS_FTHNUM                      269
#define IDS_FTHFLR                      270
#define IDS_FTHUPCNT                    271
#define IDS_FTHDWNCNT                   272
#define IDS_SETSTCH                     273
#define IDS_P2CMSG                      274
#define IDS_P2CTITL                     275
#define IDS_CLPLIM                      276
#define IDS_P2CNODAT                    277
#define IDS_CLPSPAC                     278
#define IDS_CHANSMAL                    279
#define IDS_FSTRT                       280
#define IDS_FEND                        281
#define IDS_FORMP                       282
#define IDS_WLKIND                      283
#define IDS_WLKLEN                      284
#define IDS_UANG                        285
#define IDS_USPAC                       286
#define IDS_WALK                        287
#define IDS_UWLKIND                     288
#define IDS_WLKCOL                      289
#define IDS_UND                         290
#define IDS_UNDCOL                      291
#define IDS_ULEN                        292
#define IDS_FUANG                       293
#define IDS_FUSPAC                      294
#define IDS_KEYVER                      295
#define IDC_LOCKAL                      1001
#define IDC_UNLOCKAL                    1002
#define IDC_LOCKED                      1003
#define IDC_UNLOCKED                    1004
#define IDC_LOCK                        1005
#define IDC_UNLOCK                      1006
#define IDC_RATLAB                      1006
#define IDC_TEARAT                      1007
#define IDC_TWSTLAB                     1008
#define IDC_TEARPNTS                    1009
#define IDC_TEARSIDS                    1010
#define IDC_TWRATLAB                    1011
#define IDC_TWSTSTP                     1013
#define IDC_TWRAT                       1014
#define IDC_TWSTRAT                     1015
#define IDC_DEFTEAR                     1016
#define IDC_DEFPAIS                     1017
#define IDC_WPNTXT                      1018
#define IDC_WAVPNTS                     1019
#define IDC_WAVSTRTXT                   1020
#define IDC_WAVSTRT                     1022
#define IDC_WAVENDTXT                   1023
#define IDC_WAVEND                      1024
#define IDC_WAVSTXT                     1025
#define IDC_WAVS                        1026
#define IDC_DEFWAV                      1027
#define IDC_FDUP                        1029
#define IDC_FDUPCNT                     1031
#define IDC_DFUPCNT                     1031
#define IDC_FDWN                        1032
#define IDC_FDWNCNT                     1033
#define IDC_DFDWNCNT                    1033
#define IDC_FDBLND                      1036
#define IDC_FDTYP                       1037
#define IDC_SFDRAT                      1038
#define IDC_DFRAT                       1039
#define IDC_SDFNUM                      1040
#define IDC_DFNUM                       1041
#define IDC_DFLR                        1043
#define IDC_SFDFLR                      1044
#define IDC_DAZRST                      1045
#define IDC_PETALS                      1047
#define IDC_PETLPNTS                    1048
#define IDC_CNTLEN                      1049
#define IDC_PETLEN                      1050
#define IDC_HOLSIZ                      1052
#define IDC_HOLE                        1053
#define IDC_CNTPNTS                     1054
#define IDC_COMBO1                      1055
#define IDC_INPNTS                      1056
#define IDC_DAZTYP                      1057
#define IDS_DAZCRV                      1058
#define IDS_DAZSAW                      1059
#define IDS_DAZRMP                      1060
#define IDS_DAZRAG                      1061
#define IDS_DAZCOG                      1062
#define IDC_DLIN                        1063
#define IDS_CWLK                        1063
#define IDS_UCOL                        1064
#define IDC_TWID                        1064
#define IDS_SETULEN                     1065
#define IDC_THI                         1065
#define IDS_SRTER                       1066
#define IDC_DAZPCNT                     1066
#define IDS_SETUSPAC                    1067
#define IDC_TSPAC                       1067
#define IDS_SETUANG                     1068
#define IDC_DESWID                      1068
#define IDS_SETFLEN                     1069
#define IDC_DESHI                       1069
#define IDS_SETFSPAC                    1070
#define IDS_SETFANG                     1071
#define IDS_COL                         1072
#define IDS_WID                         1073
#define IDC_REFILF                      1073
#define IDS_HI                          1074
#define IDC_DUASP                       1074
#define IDS_FRMBOX                      1075
#define IDS_HSIZ                        1076
#define IDC_DESED                       1076
#define IDS_DAZHART                     1077
#define IDS_CLEAR                       1078
#define IDS_TXHI                        1079
#define IDS_TXWID                       1080
#define IDS_TXSPAC                      1081
#define IDS_TXVRT                       1082
#define IDS_TXHOR                       1083
#define IDS_TXANG                       1084
#define IDS_FIL11                       1085
#define IDS_FIL12                       1086
#define IDS_FIL13                       1087
#define IDS_TXOF                        1088
#define IDS_NOTLIN                      1089
#define IDS_TXMIR                       1090
#define IDS_BADFLT                      1091
#define IDS_BADCLP                      1092
#define IDS_BADSAT                      1093
#define IDS_BADTX                       1094
#define IDS_FRMDAT                      1096
#define IDS_CLPDAT                      1097
#define IDS_SATDAT                      1098
#define IDS_TXDAT                       1099
#define IDS_NOTREP                      1100
#define IDS_DATREP                      1101
#define IDS_UNAM                        1102
#define ID_FILE_OPEN1                   40002
#define ID_VIEW_STCHBAK                 40003
#define ID_EDIT_RESET_COL               40006
#define ID_FILE_SAVE2                   40007
#define ZUMIN                           40008
#define VU_ZUMFUL                       40009
#define STCHLENGTH                      40010
#define ID_EDIT_SELECTCOLOR             40011
#define ID_BACK                         40013
#define ID_FILE_NEW1                    40015
#define ID_ROT                          40016
#define ID_BITCOL                       40018
#define ID_REMZERO                      40020
#define ID_KNOTS                        40021
#define ID_LODBIT                       40022
#define ID_HIDBIT                       40023
#define ID_GRDTHRSH                     40025
#define ID_SIZ30                        40026
#define ID_SIZ40                        40027
#define ID_SIZ60                        40028
#define ID_TSIZDEF                      40029
#define ID_MAXLEN                       40030
#define ID_NOMLEN                       40031
#define ID_MINLEN                       40032
#define ID_LENDEF                       40033
#define ID_RUNPAT                       40034
#define ID_FILL_VERT                    40035
#define ID_FILANG                       40036
#define ID_FILE_SAVE3                   40037
#define ID_DELSTCH                      40042
#define ID_OPNPCD                       40043
#define ID_BOXTHR                       40044
#define ID_FILSPAC                      40045
#define ID_ENTRANG                      40046
#define ID_FILSAT                       40047
#define ID_FORM                         40048
#define ID_FILENDS                      40049
#define ID_UNFIL                        40050
#define ID_SMALOF                       40051
#define ID_REDO                         40052
#define ID_FRM0                         40053
#define ID_FILIN                        40055
#define ID_FILCLP                       40056
#define ID_FILL_HOR                     40057
#define ID_SATBRD                       40058
#define ID_SBRDSIZ                      40059
#define ID_APLIQ                        40060
#define ID_REFIL                        40061
#define ID_SETAP                        40062
#define ID_ADEND                        40065
#define ID_BOLD                         40066
#define ID_PREF                         40067
#define ID_FLIPH                        40068
#define ID_FLIPV                        40069
#define ID_DELETE                       40070
#define ID_VUBAK                        40072
#define ID_PURG                         40073
#define ID_PURGDIR                      40074
#define ID_PERP                         40075
#define ID_MV2FRNT                      40076
#define ID_MV2BAK                       40077
#define ID_FRMOF                        40078
#define ID_KEYHLP                       40081
#define ID_FLPORD                       40082
#define ID_CLPFIL                       40083
#define ID_SNAP2                        40085
#define ID_DELFRMS                      40086
#define ID_ROTCMD                       40087
#define ID_ROTDUP                       40088
#define ID_ROTAGAIN                     40089
#define ID_L1                           40091
#define ID_L2                           40092
#define ID_L3                           40093
#define ID_L4                           40094
#define ID_LA                           40095
#define ID_LAYCPY1                      40097
#define ID_LAYCPY2                      40098
#define ID_LAYCPY3                      40099
#define ID_LAYCPY4                      40100
#define ID_LAYMOV1                      40101
#define ID_LAYMOV2                      40102
#define ID_LAYMOV3                      40103
#define ID_LAYMOV4                      40104
#define ID_SORT                         40105
#define ID_RTRVCLP                      40106
#define ID_CHK                          40107
#define ID_REFILAL                      40108
#define ID_SELAL                        40109
#define ID_DELFRE                       40110
#define ID_LAYMOV0                      40112
#define ID_LAYCPY0                      40113
#define ID_SETMRK                       40114
#define ID_SELFIL                       40115
#define ID_SELBRD                       40116
#define ID_SELAP                        40117
#define ID_SELFSTCHS                    40118
#define ID_MOVMRK                       40119
#define ID_VUTHRDS                      40120
#define ID_VUSELTHRDS                   40121
#define ID_REMBIG                       40122
#define ID_FILBUT                       40123
#define ID_PICOT                        40125
#define ID_THUM                         40126
#define ID_CONTF                        40127
#define ID_UNGRPLO                      40128
#define ID_UNGRPHI                      40129
#define ID_SELALSTCH                    40130
#define ID_INSFIL                       40131
#define ID_CNTR                         40132
#define ID_HLP                          40134
#define ID_ZUMOUT                       40135
#define ID_DESIZ                        40136
#define ID_ABOUT                        40137
#define ID_REFILF                       40138
#define ID_RIBON                        40139
#define ID_AUXPCS                       40141
#define ID_AUXDST                       40142
#define ID_DELTOT                       40143
#define ID_CLPADJ                       40144
#define ID_DUPAGAIN                     40145
#define ID_SHRINK                       40146
#define ID_SETPREF                      40147
#define ID_SETROT                       40148
#define ID_MRKCNTR                      40149
#define ID_ROTMRK                       40150
#define ID_ROTSEG                       40151
#define ID_MRKPNT                       40152
#define ID_FRMNUM                       40153
#define ID_CNTRH                        40154
#define ID_CNTRV                        40155
#define ID_CNTRX                        40156
#define ID_CENTIRE                      40157
#define ID_SRTBF                        40158
#define ID_DUBEAN                       40159
#define ID_UNBEAN                       40160
#define ID_SPLTFRM                      40161
#define ID_STCHS2FRM                    40162
#define ID_SETNEDL                      40165
#define ID_RSTNEDL                      40166
#define ID_DELKNOT                      40167
#define ID_KNOTON                       40168
#define ID_KNOTOF                       40169
#define ID_BSAVON                       40170
#define ID_BSAVOF                       40171
#define ID_LINBEXACT                    40173
#define ID_LINBEVEN                     40174
#define ID_VRTCLP                       40176
#define ID_HORCLP                       40177
#define ID_ANGCLP                       40178
#define ID_DUBFIL                       40179
#define ID_RETRACE                      40180
#define ID_GRDEF                        40181
#define ID_GRDHI                        40182
#define ID_GRDMED                       40183
#define ID_GRDRED                       40184
#define ID_GRDBLU                       40185
#define ID_GRDGRN                       40186
#define ID_OVRLAY                       40188
#define ID_FIL2SEL_ON                   40190
#define ID_FIL2SEL_OFF                  40191
#define ID_SNAP2GRD                     40192
#define ID_FRM2COL                      40193
#define ID_ROTAUXON                     40194
#define ID_ROTAUXOFF                    40195
#define ID_FLOK                         40196
#define ID_TRACE                        40198
#define ID_TRDIF                        40199
#define ID_TRCSEL                       40200
#define ID_TRACEDG                      40201
#define ID_SAVMAP                       40202
#define ID_BLAK                         40203
#define ID_HIDBITF                      40204
#define ID_DELMAP                       40205
#define ID_CLOSE                        40206
#define ID_LINCHN                       40207
#define ID_OPNCHN                       40208
#define ID_NUDGPIX                      40209
#define ID_MARKESC                      40210
#define ID_MARKQ                        40211
#define ID_BAKMRK                       40213
#define ID_CROP                         40214
#define ID_STCHPIX                      40215
#define ID_FRMPIX                       40216
#define ID_SEP                          40219
#define ID_KNOTAT                       40220
#define ID_FRMBOX                       40222
#define ID_FRMX                         40223
#define ID_FILCLPX                      40224
#define ID_SRTF                         40225
#define ID_FTHDEF                       40238
#define ID_FETHR                        40239
#define ID_2FTHR                        40240
#define ID_PES2CRD                      40241
#define ID_CLPSPAC                      40242
#define ID_FILSTRT                      40243
#define ID_FILEND                       40244
#define ID_WIND                         40245
#define ID_USTCH                        40246
#define ID_USPAC                        40247
#define ID_UANG                         40248
#define ID_ALFRM                        40249
#define ID_SELWLK                       40250
#define ID_SELUND                       40251
#define ID_SETUND                       40253
#define ID_SETWLK                       40254
#define ID_SETCWLK                      40255
#define ID_NOTCWLK                      40256
#define ID_NOTWLK                       40257
#define ID_NOTUND                       40258
#define ID_UNDLEN                       40259
#define ID_SETUSPAC                     40261
#define ID_SETUANG                      40262
#define ID_SETFLEN                      40263
#define ID_SETFSPAC                     40264
#define ID_SETFANG                      40265
#define ID_SETUCOL                      40266
#define ID_SETFCOL                      40267
#define ID_SETBCOL                      40268
#define ID_SETBLEN                      40269
#define ID_SETBSPAC                     40270
#define ID_MAXBLEN                      40271
#define ID_MINBLEN                      40272
#define ID_MAXFLEN                      40273
#define ID_MINFLEN                      40274
#define ID_FRMWID                       40275
#define ID_FRMHI                        40276
#define ID_FRMPBOX                      40277
#define ID_TXFIL                        40282
#define ID_SETSIZ                       40283
#define ID_FRMIND                       40284
#define ID_WARNOF                       40285
#define ID_CHKOF                        40286
#define ID_REPAIR                       40287
#define ID_CHKON                        40288
#define ID_CHKREP                       40289
#define ID_CHKREPMSG                    40290
#define ID_VIEW_SET_DATACHECK           40291
#define ID_DESNAM                       40292

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40293
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
